### ISSUE TITLE
Mocking causes NullPointerException when running under Test Orchestrator

### ISSUE THREAD

**Issue by damianw** [linkedin/dexmaker#115]
Running tests on a P device with `connectedAndroidTest` runs fine, but crashes when using the [Android Test Orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator), throwing the following:

```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.mockito.plugins.MockMaker$TypeMockability.mockable()' on a null object reference
at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:23)
at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:238)
at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
at org.mockito.Mockito.mock(Mockito.java:1895)
at org.mockito.Mockito.mock(Mockito.java:1804)
...
```

In my case, I am using the Test Orchestrator for running on Firebase.

**Comment by moltmann** [comment]
Can you give me some more information:

- What variant and version of dexmaker-mockito are you using.
- Can you post the whole log of the test (and a little before and after)?

**Comment by damianw** [comment]
Apologies - after investigating the logs more closely, it is an issue with Firebase where tests run on P preview API 27 despite specifying API 28, failing [this API level check](https://github.com/linkedin/dexmaker/blob/master/dexmaker-mockito-inline/src/main/java/com/android/dx/mockito/inline/JvmtiAgent.java#L54-L57). I have filed an issue with Firebase support instead.
