### ISSUE TITLE
java.lang.NoClassDefFoundError: org.mockito.internal.util.MockCreationValidator

### ISSUE THREAD

**Issue by jaredsburrows** [linkedin/dexmaker#63]
## Explanation:
Swapping out Google's dexmaker with LinkedIn's dexmaker, I am getting the following error. From what I can tell, the LinkedIn version of the dexmaker is so much larger that it causes the Android Test APK to become Multidex. 

I have tried the following: https://stackoverflow.com/questions/30081386/how-to-put-specific-classes-into-main-dex-file and https://stackoverflow.com/questions/34310259/trying-to-test-an-android-module-in-multidex-app-com-android-test-runner-multid.

Any way to avoid this?

## Error:
```
D/AndroidRuntime( 2960): Shutting down VM
    E/AndroidRuntime( 2970): FATAL EXCEPTION: main
    E/AndroidRuntime( 2970): Process: <>, PID: 2970
    E/AndroidRuntime( 2970): java.lang.NoClassDefFoundError: org.mockito.internal.util.MockCreationValidator
    E/AndroidRuntime( 2970): 	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:166)
    E/AndroidRuntime( 2970): 	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
    E/AndroidRuntime( 2970): 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
    E/AndroidRuntime( 2970): 	at org.mockito.Mockito.mock(Mockito.java:1637)
    E/AndroidRuntime( 2970): 	at org.mockito.Mockito.mock(Mockito.java:1550)
    ...
    E/AndroidRuntime( 2970): 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    ...
    E/AndroidRuntime( 2970): 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    ...
    E/AndroidRuntime( 2970): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    E/AndroidRuntime( 2970): 	at android.support.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:323)
    E/AndroidRuntime( 2970): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
    E/AndroidRuntime( 2970): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
    E/AndroidRuntime( 2970): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
    E/AndroidRuntime( 2970): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime( 2970): 	at android.os.Looper.loop(Looper.java:136)
    E/AndroidRuntime( 2970): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
    E/AndroidRuntime( 2970): 	at java.lang.reflect.Method.invokeNative(Native Method)
    E/AndroidRuntime( 2970): 	at java.lang.reflect.Method.invoke(Method.java:515)
    E/AndroidRuntime( 2970): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    E/AndroidRuntime( 2970): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    E/AndroidRuntime( 2970): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by drewhannay** [comment]
The number of methods in the actual dexmaker project hasn't changed...from what I can tell, this is due to upgrading to a newer version of Mockito, which depends transitively on bytebuddy.

I did some investigation and opened this issue on the mockito repo:
https://github.com/mockito/mockito/issues/1112

If they can reduce their method count, we can also update dexmaker to pull in the newer version of Mockito.

**Comment by tmurakami** [comment]
Hi.

@jaredsburrows, DexMaker has its own MockMaker, so I think that you can exclude Byte Buddy from your test apk.

```
dependencies {
    androidTestCompile('com.linkedin.dexmaker:dexmaker-mockito:x.y.z') {
        exclude group: 'net.bytebuddy'
    }
}
```

**Comment by jaredsburrows** [comment]
http://www.methodscount.com/?lib=com.linkedin.dexmaker%3Adexmaker-mockito%3A%2B

Thanks. Makes sense to me!

**Comment by drewhannay** [comment]
Please let me know if that solution works for you, I'm very interested to find out.

**Comment by jaredsburrows** [comment]
@drewhannay I just wanted to confirm that it works by excluding `net.bytebuddy`.

@tmurakami Thank you. That works! Does this mean I cannot mock `final` when using Mockito 2?

**Comment by tmurakami** [comment]
@jaredsburrows, you can still use Mockito 2 with Byte Buddy to mock final classes for local unit testing.

```
dependencies {

    // For local unit tests (on your develop machine)
    testCompile 'org.mockito:mockito-inline:x.y.z'

    // For instrumented unit tests (on Android emulators and devices)
    androidTestCompile('com.linkedin.dexmaker:dexmaker-mockito:x.y.z') {
        exclude group: 'net.bytebuddy'
    }

}
```

If you are using Kotlin and would like to mock final classes on Android emulators and devices, please refer to https://github.com/mockito/mockito/issues/1082#issuecomment-301646307.

**Comment by jaredsburrows** [comment]
I use Mockito 2 just fine in unit tests(`testCompile`), but if we exclude `net.bytebuddy` from `dexmaker-mockito`, how can you mock `final`? Isn't `net.bytebuddy` for code generation? Why does Mockito 2 include as a transitive dependency?

**Comment by tmurakami** [comment]
@jaredsburrows,

```
dependencies {

    // For local unit tests (on your develop machine)
    testCompile 'org.mockito:mockito-inline:2.8.9'

    // For instrumented unit tests (on Android emulators and devices)
    androidTestCompile('com.linkedin.dexmaker:dexmaker-mockito:2.2.0') {
        exclude group: 'net.bytebuddy'
    }

}
```

Running `./gradlew androidDependencies` with the above code will get the following result.
```
$ ./gradlew androidDependencies
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/tmura/android-sdk-linux/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use the method ConfigurableReport.setDestination(File) instead.
:app:androidDependencies
debug
No dependencies

debugAndroidTest
\--- com.linkedin.dexmaker:dexmaker-mockito:2.2.0@jar
     +--- com.linkedin.dexmaker:dexmaker:2.2.0@jar
     |    \--- com.jakewharton.android.repackaged:dalvik-dx:7.1.0_r7@jar
     |         \--- com.jakewharton.android.repackaged:libcore-dex:7.1.0_r7@jar
     \--- org.mockito:mockito-core:2.2.29@jar
          \--- org.objenesis:objenesis:2.4@jar

debugUnitTest
\--- org.mockito:mockito-inline:2.8.9@jar
     \--- org.mockito:mockito-core:2.8.9@jar
          +--- net.bytebuddy:byte-buddy:1.6.14@jar
          +--- net.bytebuddy:byte-buddy-agent:1.6.14@jar
          \--- org.objenesis:objenesis:2.5@jar

release
No dependencies

releaseUnitTest
\--- org.mockito:mockito-inline:2.8.9@jar
     \--- org.mockito:mockito-core:2.8.9@jar
          +--- net.bytebuddy:byte-buddy:1.6.14@jar
          +--- net.bytebuddy:byte-buddy-agent:1.6.14@jar
          \--- org.objenesis:objenesis:2.5@jar

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed, 0 avoided (0%)
```

Byte Buddy is used for `MockMaker` of Mockito, so it is required for local unit testing.
However, since DexMaker has its own `MockMaker` which does not rely on Byte Buddy, it can be excluded from dependencies scoped as `androidTestCompile`.

FYI, Mockito does not support mock final on Android.

https://static.javadoc.io/org.mockito/mockito-core/2.8.9/org/mockito/Mockito.html#0.1
```
Be aware that you cannot use the inline mock maker on Android due to limitations in the Android VM.
```

**Comment by jaredsburrows** [comment]
Great explantation! Thanks again!
> Byte Buddy is used for MockMaker of Mockito, so it is required for local unit testing.
> However, since DexMaker has its own MockMaker which does not rely on Byte Buddy, it can be excluded from dependencies scoped as androidTestCompile.
> 
> FYI, Mockito does not support mock final on Android.
