### ISSUE TITLE
java.lang.ClassNotFoundException: com.android.dex.DexIndexOverflowException

### ISSUE THREAD

**Issue by jaredsburrows** [linkedin/dexmaker#65]
## Environment:

Test repo: https://github.com/jaredsburrows/android-gif-example/pull/12/commits/9a26ca9dbed75d8487717ce24feab701d9b95388

## Repro steps:
 - When I change Espresso to `3.0` and the Runner to `1.0.0`, I get the following error.
 - `gradlew connectedDebugAndroidTest`

## Error:
```
java.lang.ClassNotFoundException: com.android.dex.DexIndexOverflowException
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:76)
at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:808)
at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:481)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:367)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
Caused by: java.lang.NoClassDefFoundError: com/android/dex/DexIndexOverflowException
... 8 more
Caused by: java.lang.IncompatibleClassChangeError: superclass is final
at dalvik.system.DexFile.defineClassNative(Native Method)
at dalvik.system.DexFile.defineClass(DexFile.java:222)
at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
at dalvik.system.DexPathList.findClass(DexPathList.java:322)
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
... 8 more
```

## Fixes?
The missing class is coming from: https://github.com/JakeWharton/dalvik-dx, a dependency in the project
 - Revert back to Mockito 1 and DexMakerMockito 1?
 - Use stubs and not mocks?

**Comment by tmurakami** [comment]
Hi.

I guess this error occurs only on Android 4.4.

Since Android 4.4, several classes under the package `com.android.dex` are now included in the Android system.
However on Android 4.4, some of them are incompatible with Jake's `libcore-dex` artifact.
`DexIndexOverflowException` is subclass of `DexException`, but on Android 4.4, `DexException` is final.
As a result, `IncompatibleClassChangeError: superclass is final` occurs while AndroidJUnitRunner is looking for a `org.junit.runner.Runner` subclass.

To avoid this, filter out `DexIndexOverflowException` from the classes that AndroidJUnitRunner scans.

```groovy
android {
    defaultConfig {
         testInstrumentationRunnerArguments.notClass = 'com.android.dex.DexIndexOverflowException'
    }
}
```

**Comment by jaredsburrows** [comment]
@tmurakami Wow. Thanks for the fast response. How did you find that out so quickly? 

I was writing a task to repackage it completely, this works much better!

For Kotlin DSL, use `testInstrumentationRunnerArguments["notClass"] = "com.android.dex.DexIndexOverflowException"`.

https://github.com/jaredsburrows/android-gif-example/pull/12/files#diff-392475fdf2bc320d17762ed97109a121R63
