### ISSUE TITLE
Could not initialize plugin: interface org.mockito.plugins.MockMaker

### ISSUE THREAD

**Issue by nikhilsol89** [linkedin/dexmaker#99]
Hi Team,
Getting the below mentioned error when included the 
androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.16.0' in the build.gradle.

The cause shows that net.bytebuddy.matcher.ElementMatchers is not found, which was removed explicitly in the release.
Below is the stack trace.
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy7.isTypeMockable(Unknown Source)
at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:232)
at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
at org.mockito.Mockito.mock(Mockito.java:1864)
at org.mockito.Mockito.mock(Mockito.java:1777)
at com.xyz.example.ui.base.modules.CommanApiTestModule.provideEndpoint(CommanApiTestModule.java:35)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideEndpointFactory.get(CommanApiTestModule_ProvideEndpointFactory.java:19)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideEndpointFactory.get(CommanApiTestModule_ProvideEndpointFactory.java:8)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideRetrofitFactory.get(CommanApiTestModule_ProvideRetrofitFactory.java:46)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideRetrofitFactory.get(CommanApiTestModule_ProvideRetrofitFactory.java:13)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesNetworkServiceFactory.get(ApiTestModule_ProvidesNetworkServiceFactory.java:26)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesNetworkServiceFactory.get(ApiTestModule_ProvidesNetworkServiceFactory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesServiceFactory.get(ApiTestModule_ProvidesServiceFactory.java:26)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesServiceFactory.get(ApiTestModule_ProvidesServiceFactory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.exampleseeker.ui.login.OtpPresenter_MembersInjector.injectMembers(OtpPresenter_MembersInjector.java:35)
at com.xyz.exampleseeker.ui.login.OtpPresenter_MembersInjector.injectMembers(OtpPresenter_MembersInjector.java:9)
at dagger.internal.MembersInjectors.injectMembers(MembersInjectors.java:37)
at com.xyz.exampleseeker.ui.login.OtpPresenter_Factory.get(OtpPresenter_Factory.java:18)
at com.xyz.exampleseeker.ui.login.OtpPresenter_Factory.get(OtpPresenter_Factory.java:8)
at com.xyz.example.ui.base.modules.seeker.LoginTestModule_ProvideOtpPresenterFactory.get(LoginTestModule_ProvideOtpPresenterFactory.java:27)
at com.xyz.example.ui.base.modules.seeker.LoginTestModule_ProvideOtpPresenterFactory.get(LoginTestModule_ProvideOtpPresenterFactory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.login.OtpFragmentInstrumentationTest_MembersInjector.injectMembers(OtpFragmentInstrumentationTest_MembersInjector.java:36)
at com.xyz.example.ui.login.OtpFragmentInstrumentationTest_MembersInjector.injectMembers(OtpFragmentInstrumentationTest_MembersInjector.java:9)
at com.xyz.example.ui.base.components.DaggerSeekerAppTestComponent$LoginTestSubComponentImpl.inject(DaggerSeekerAppTestComponent.java:1567)
at com.xyz.example.ui.login.OtpFragmentInstrumentationTest.setUp(OtpFragmentInstrumentationTest.java:56)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:385)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2136)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/bytebuddy/matcher/ElementMatchers;
at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.<init>(SubclassBytecodeGenerator.java:54)
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.<init>(SubclassByteBuddyMockMaker.java:37)
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.<init>(SubclassByteBuddyMockMaker.java:33)
at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.<init>(ByteBuddyMockMaker.java:21)
at java.lang.Class.newInstance(Native Method)
at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:66)
at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.getDefaultPlugin(DefaultMockitoPlugins.java:43)
at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:67)
at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:18)
at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:34)
at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
... 62 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.bytebuddy.matcher.ElementMatchers" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.xyz.example.debug.test-JPbCQCwit0DQb7CwHpsH_A==/base.apk", zip file "/data/app/com.xyz.example.debug-7eFx6EDFhN6rL1u6Z4hqVg==/base.apk"],nativeLibraryDirectories=[/data/app/com.xyz.example.debug.test-JPbCQCwit0DQb7CwHpsH_A==/lib/x86, /data/app/com.xyz.example.debug-7eFx6EDFhN6rL1u6Z4hqVg==/lib/x86, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 75 more

**Comment by nikhilsol89** [comment]
@drewhannay  Could you please have a look into the issue.

**Comment by moltmann** [comment]
Mockito should not even try to init ByteBuddyMockMaker. My guess is that you are missing the mockito-extensions/org.mockito.plugins.MockMaker file that should come in the dexmaker-mockito-inline dependency.

**Comment by nikhilsol89** [comment]
@moltmann  I have explicitly put the file at the location app/src/androidTest/resources/mockito-extensions/org.mockito.plugins.MockMaker and added only a single line --- mock-maker-inline in the file, but still I am getting the same issue. I am attaching a snap of my build.gradle as well for your reference.
Please suggest where I could be going wrong

// Espresso dependencies
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation "com.android.support.test.espresso:espresso-core:$espressoVersion"
    androidTestImplementation "com.android.support.test.espresso:espresso-contrib:$espressoVersion"
    androidTestImplementation "com.android.support.test.espresso:espresso-intents:$espressoVersion"
    androidTestImplementation "com.android.support.test.espresso:espresso-accessibility:$espressoVersion"
    androidTestImplementation "com.android.support.test.espresso:espresso-web:$espressoVersion"
    androidTestImplementation "com.android.support.test.espresso.idling:idling-concurrent:$espressoVersion"


    //testImplementation 'org.mockito:mockito-core:2.16.0'

    //androidTestImplementation 'org.mockito:mockito-core:2.16.0'

    //androidTestImplementation 'org.mockito:mockito-android:2.7.22'
    
    androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.16.0'

    /*androidTestImplementation 'com.google.dexmaker:dexmaker:1.2'
            androidTestImplementation 'com.google.dexmaker:dexmaker-mockito:1.2'*/

**Comment by moltmann** [comment]
@nikhilsol89 Don't add your own file, the file should come as part of the dexmaker-mockito-inline.

**Comment by nikhilsol89** [comment]
@moltmann  Earlier I did not add it explicitly, then also it was failing, I am trying to mock the HttpUrl Class which is a final class, can you please have a look at the gradle file I posted and suggest what I am missing or where it could be failing.

**Comment by moltmann** [comment]
The gradle file should work. What is the failure you are getting when trying to mock HttpUrl?

**Comment by drewhannay** [comment]
@nikhilsol89 Just to double check, you're trying to run these tests on a device running Android P DP 1, correct?

**Comment by nikhilsol89** [comment]
@moltmann The stack trace attached is the failure i am getting when I am trying to mock the  HttpUrl Class.

java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null).
.
.
.
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.bytebuddy.matcher.ElementMatchers"

It is the same stack trace attached in the first comment.

@drewhannay Yes I am running it on an emulator running on Android DP 1, whereas the target SDK version is 25 and compile SDK version is API 26. Please suggest.

**Comment by moltmann** [comment]
Sorry, I mean the stack trace when you don't manually add a extensions/org.mockito.plugins.MockMaker file.

**Comment by nikhilsol89** [comment]
@moltmann Its the same for both the cases, however I am still attaching the stack trace again.

java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy7.isTypeMockable(Unknown Source)
at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:232)
at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
at org.mockito.Mockito.mock(Mockito.java:1864)
at org.mockito.Mockito.mock(Mockito.java:1777)
at com.xyz.example.ui.base.modules.CommanApiTestModule.provideEndpoint(CommanApiTestModule.java:35)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideEndpointFactory.get(CommanApiTestModule_ProvideEndpointFactory.java:19)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideEndpointFactory.get(CommanApiTestModule_ProvideEndpointFactory.java:8)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideRetrofitFactory.get(CommanApiTestModule_ProvideRetrofitFactory.java:46)
at com.xyz.example.ui.base.modules.CommanApiTestModule_ProvideRetrofitFactory.get(CommanApiTestModule_ProvideRetrofitFactory.java:13)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesNetworkServiceFactory.get(ApiTestModule_ProvidesNetworkServiceFactory.java:26)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesNetworkServiceFactory.get(ApiTestModule_ProvidesNetworkServiceFactory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesServiceFactory.get(ApiTestModule_ProvidesServiceFactory.java:26)
at com.xyz.example.ui.base.modules.seeker.ApiTestModule_ProvidesServiceFactory.get(ApiTestModule_ProvidesServiceFactory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.exampleseeker.ui.login.OtpPresenter_MembersInjector.injectMembers(OtpPresenter_MembersInjector.java:35)
at com.xyz.exampleseeker.ui.login.OtpPresenter_MembersInjector.injectMembers(OtpPresenter_MembersInjector.java:9)
at dagger.internal.MembersInjectors.injectMembers(MembersInjectors.java:37)
at com.xyz.exampleseeker.ui.login.OtpPresenter_Factory.get(OtpPresenter_Factory.java:18)
at com.xyz.exampleseeker.ui.login.OtpPresenter_Factory.get(OtpPresenter_Factory.java:8)
at com.xyz.example.ui.base.modules.seeker.LoginTestModule_ProvideOtpPresenterFactory.get(LoginTestModule_ProvideOtpPresenterFactory.java:27)
at com.xyz.example.ui.base.modules.seeker.LoginTestModule_ProvideOtpPresenterFactory.get(LoginTestModule_ProvideOtpPresenterFactory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.xyz.example.ui.login.OtpFragmentInstrumentationTest_MembersInjector.injectMembers(OtpFragmentInstrumentationTest_MembersInjector.java:36)
at com.xyz.example.ui.login.OtpFragmentInstrumentationTest_MembersInjector.injectMembers(OtpFragmentInstrumentationTest_MembersInjector.java:9)
at com.xyz.example.ui.base.components.DaggerSeekerAppTestComponent$LoginTestSubComponentImpl.inject(DaggerSeekerAppTestComponent.java:1567)
at com.xyz.example.ui.login.OtpFragmentInstrumentationTest.setUp(OtpFragmentInstrumentationTest.java:56)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:385)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2136)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/bytebuddy/matcher/ElementMatchers;
at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.<init>(SubclassBytecodeGenerator.java:54)
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.<init>(SubclassByteBuddyMockMaker.java:37)
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.<init>(SubclassByteBuddyMockMaker.java:33)
at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.<init>(ByteBuddyMockMaker.java:21)
at java.lang.Class.newInstance(Native Method)
at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:66)
at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.getDefaultPlugin(DefaultMockitoPlugins.java:43)
at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:67)
at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:18)
at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:34)
at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
... 62 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.bytebuddy.matcher.ElementMatchers" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.xyz.example.debug.test-JPbCQCwit0DQb7CwHpsH_A==/base.apk", zip file "/data/app/com.xyz.example.debug-7eFx6EDFhN6rL1u6Z4hqVg==/base.apk"],nativeLibraryDirectories=[/data/app/com.xyz.example.debug.test-JPbCQCwit0DQb7CwHpsH_A==/lib/x86, /data/app/com.xyz.example.debug-7eFx6EDFhN6rL1u6Z4hqVg==/lib/x86, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 75 more

**Comment by moltmann** [comment]
If you don't have any other mockito loaded and did not set extensions/org.mockito.plugins.MockMaker the trace should not happen. Can you unzip your androidtest apk and check what extensions/org.mockito.plugins.MockMaker is set to?

**Comment by nikhilsol89** [comment]
@moltmann I have made sure that no other mockito  is being loaded and I am also not able to find extensions/org.mockito.plugins.MockMaker in the unzipped apk, and is not found in the extracted apk.

**Comment by moltmann** [comment]
Are you sure that you
- looked at the androidTest apk
- You have a dependency on dexmaker-mockito-inline 

In this case you will have a extensions/org.mockito.plugins.MockMaker pointing to dexmaker.

You need to figure out what is wrong in the build.

**Comment by nikhilsol89** [comment]
@moltmann I made sure that I have a dependency on dexmaker-mockito-inline only and no other mockito dependency of any type, as you can see from build.gradle posted above.
Also in the extracted androidTest apk, I am not able to find  extensions/org.mockito.plugins.MockMaker anywhere, could you please let me know where exactly to look out for this?.

**Comment by nikhilsol89** [comment]
@drewhannay Yes it would be really helpful, if you can post this sample project for me to compare. Also the HttpUrl class I am mocking is coming through OkHttp3 dependency.
Moreover I am using Dagger 2 for injecting the HttpUrl Dependency into my android instrumentation test classes.

**Comment by drewhannay** [comment]
@nikhilsol89 I pushed my demo repo here: https://github.com/drewhannay/dexmaker-inline-okhttp-demo

**Comment by nikhilsol89** [comment]
@drewhannay  Thanks Drew, I will have a look at this and get back to you with further updates.

**Comment by nikhilsol89** [comment]
HI @drewhannay @moltmann Thanks for the git hub repo demo code, I am able to make my way through the issue I was facing but unfortunately I landed up into another issue related to the library only.

As this library works only on devices running android P DP1, I am getting the error "Detected problem with API comptability" when I run my espresso Instrumentation tests. 
Could you please help me out with the same.

**Comment by drewhannay** [comment]
That sounds like an issue with Espresso, not dexmaker. You can open an issue at issuetracker.google.com for the Espresso team to help.

I'm going to close this issue for now, but let us know if you encounter any more dexmaker-specific issues.

**Comment by tmehta813** [comment]
having the same issue
